perf/refactor(client): cache skin to avoid server callbacks + replace k, v loops with numeric for loops
esx-framework/esx_barbershop pull request #18
Opened 2024-01-14 23:19 UTC by itsmaty

I just came across this code, i was bored and I thought that I could also contribute something small to the project.

Commit 37016689d5abd56f73f5828355181f42bef97a04

I was wondering why whenever the skin, before entering the shop has to be reloaded, a server callback is made to load the skin. Thats unnecessary, now the skin gets cached before the menu opens and gets loaded from the cache whenever needed.

```
while not currentSkin do
    Wait(10)
end
```
This just makes sure that the event callback has already returned the current skin and loaded it into the cache.

Commit 6b35a88a5313360b252ed04cd4fdc1795ee39c2c

I just replaced the two for ` k, v ipairs` loops with numeric for loops to increase performance a bit

2024-01-16 18:43 UTC, Gellipapa requested changes

2024-01-16 19:07 UTC, itsmaty commented
> Hi! @itsmaty Thanks for helping me to make the project better. At this point the question arises if it would be better to store the skin on xPlayer or in its metadata and retrieve it via statebag or PlayerData so we can cache it.
> 
> What do you think about this?

I am not familiar how the esx playerdata / metadata system works. Is it like a 'real' statebag system, so data you set client or server side gets automatically synced?

Would probably be cool to have the whole skin logic inside the es_extended resource without relying on skinchnager.

But as a first step you could mirror the skin to a variable on xPlayer

2024-01-16 19:08 UTC, Gellipapa commented on client/main.lua
> +	while not cachedSkin do
> What do you mean?
> 
> `skinchanger:getSkin` always has a callback. If it happens so that no skin is set in skinchnager, which is very unlikely because on player load the skin from the database gets loaded onto the player as far as i know, the callback still returns an empty table so it dosent wait endlessly.

Yes it's legitimate I thought nil-t give back, I remembered wrong that part is irrelevant.

2024-01-16 19:09 UTC, Gellipapa commented
> > Hi! @itsmaty Thanks for helping me to make the project better. At this point the question arises if it would be better to store the skin on xPlayer or in its metadata and retrieve it via statebag or PlayerData so we can cache it.
> > What do you think about this?
> 
> I am not familiar how the esx playerdata / metadata system works. Is it like a 'real' statebag system, so data you set client or server side gets automatically synced?
> 
> Would probably be cool to have the whole skin logic inside the es_extended resource without relying on skinchnager.
> 
> But as a first step you could mirror the skin to a variable on xPlayer

That's exactly what I was thinking.

2024-01-16 20:00 UTC, itsmaty commented
Thats probably up to you or another member of the esx core team, if and how you design such a feature.
Could be discussed in an feature request issue because its not really related to this pr.

2024-01-16 20:04 UTC, itsmaty commented on client/main.lua
> +	while not cachedSkin do
Yea, i looked it up before to make sure what it returns. Forget to metion that this change has been tested.
But the loop is needed because the callback is async, so its technically possible that it dosent retun the skin so fast.

2024-01-17 08:48 UTC, KentaKK requested changes

2024-01-17 08:48 UTC, KentaKK commented on client/main.lua
> +      		local blip = AddBlipForCoord(v)
```suggestion
      		local blip = AddBlipForCoord(Config.Shops[i])
```

2024-01-17 08:48 UTC, KentaKK commented on client/main.lua
>  			local distance = #(playerCoords - v)
```suggestion
			local distance = #(playerCoords - Config.Shops[y])
```

2024-01-17 21:44 UTC, Gellipapa approved these changes
It's okey, thank you for this cache solution.

2024-01-17 21:44 UTC, merged